export const portfolioData = {
  personalInfo: {
    name: 'Vasanthakumar B',
    title: 'Fullstack Developer',
    email: 'vasanth2004vk@gmail.com',
    phone: '9514203043',
    linkedin: 'https://linkedin.com/in/vasantha-kumar-b',
    github: 'https://github.com/vasanthvk77',
    profileSummary: `Python Developer with hands-on experience in building backend systems, automation workflows, and data-driven applications using Python, FastAPI, Flask, SQL, and MongoDB. Currently working as a Trainee Python Developer at Cygnus Software with exposure to AI-powered automation, ETL workflows, and backend API development. Strong understanding database operations, and system integration.`,
  },
  skills: {
    'Programming & Backend': ['Python', 'Flask', 'FastAPI', '.NET', 'MySQL', 'PostgreSQL', 'SQL Server', 'MongoDB'],
    'Core Concepts': ['Data Structures', 'OOPS', 'REST API Development', 'ETL', 'AI Automation'],
    'Frontend Exposure': ['HTML', 'CSS', 'Bootstrap', 'React', 'Flutter', 'Three.js'],
    'Tools & Platforms': ['Git', 'Railway', 'VS Code', 'Cursor', 'Antigravity', 'Vercel'],
    'Additional Skills': ['JSON', 'Agile Methodologies', 'Video Editing (DaVinci Resolve)', 'Photo Editing (Canva)'],
  },
  experience: [
    {
      role: 'Full Stack Developer',
      company: 'Prodesx Info Tech',
      date: 'March 2026 – Present',
      location: 'Coimbatore, Tamil Nadu',
      description: [
        'Designed and implemented responsive frontend user interfaces using React and modern component libraries.',
        'Developed scalable RESTful APIs with Python FastAPI and integrated them with SQL/NoSQL databases.',
        'Collaborated on backend database architecture, optimization, and automation workflows.',
        'Participated in code reviews, testing, and continuous integration pipelines for high-availability systems.'
      ],
    },
    {
      role: 'Fullstack Developer',
      company: 'Cygnus Softwares',
      date: 'June 2025 – March 2026',
      location: 'Coimbatore, Tamil Nadu',
      description: [
        'Developed backend APIs using Python FastAPI and Flask for web and desktop applications.',
        'Implemented authentication, CRUD operations, and database integration using SQL and MongoDB.',
        'Worked on automating data extraction, database updates, and ETL tasks using Python.',
        'Built automation pipelines that extract information from emails, classify data using AI, and generate automated responses.',
        'Contributed to systems involving speech-to-text processing, accessibility analysis, and backend-driven data workflows.',
        'Implemented intelligent ETL workflows that ingest large CSV/TSV files, apply AI-driven classification and SQL-based transformations.',
        'Performed requirement analysis and unit and functional testing.',
        'Conducted testing of Python systems, debugging issues, and supporting deployments.',
      ],
    },
  ],
  projects: [
    {
      title: 'ADA Checker Web Application',
      category: 'Web Accessibility',
      subtitle: 'Audit & Compliance Tool',
      company: 'Prodesx Tech',
      tech: ['React', 'Python FastAPI', 'JavaScript'],
      description: 'Worked on an ADA Checker web application that scans websites for ADA and WCAG accessibility violations. Built a FastAPI backend to audit URLs and generate detailed, actionable accessibility reports.',
      image: '/portfolio/images/ada_checker.png',
      tags: ['Accessibility Audit', 'WCAG 2.1', 'FastAPI Backend'],
      github: 'https://github.com/vasanthvk77/ada-checker',
    },
    {
      title: 'ATM Transaction Web Application',
      category: 'FinTech',
      subtitle: 'Banking Simulation',
      company: 'Personal Project',
      tech: ['React', 'Python Flask', 'SQL'],
      description: 'Developed a web application simulating ATM operations, including login, balance checking, deposits, withdrawals, and transaction history.',
      image: '/portfolio/images/atm.png',
      tags: ['Transaction Logic', 'SQL Integration', 'Secure Login'],
      github: 'https://github.com/vasanthvk77/atm-transaction',
    },
    {
      title: 'Sales Enquiry Automation',
      category: 'AI Automation',
      subtitle: 'Intelligent Lead Management',
      company: 'Cygnus Softwares',
      tech: ['React', 'Python FastAPI', 'MySQL'],
      description: 'Worked on a hotel sales-enquiry automation system that reads inbound emails, classifies them using AI, extracts key details, and sends acknowledgement and manager summary emails automatically.',
      image: '/portfolio/images/sales_enquiry.png',
      tags: ['AI Classification', 'Email Processing', 'Automation'],
      github: 'https://github.com/vasanthvk77/sales-enquiry-automation',
    },
    {
      title: 'Sign Language Generation',
      category: 'AI & Accessibility',
      subtitle: 'Spoken Audio to Sign Animation',
      company: 'Academic Project',
      tech: ['HTML', 'CSS', 'Javascript', 'Python Flask'],
      description: 'Developed an intelligent system that converts spoken audio into text and then translates that text into sign-language animations.',
      image: '/portfolio/images/sign_language.png',
      tags: ['Speech-to-Text', '3D Animations', 'Accessibility'],
      github: 'https://github.com/vasanthvk77/sign-language-generator',
    },
    {
      title: 'Candor Data Platform',
      category: 'Data Engineering',
      subtitle: 'Visual ETL Pipeline',
      company: 'Cygnus Softwares',
      tech: ['Typescript', 'Python FastAPI', 'MySQL', 'PostgreSQL'],
      description: 'Worked on a desktop ETL platform that lets users visually define, configure, and run complete data pipelines, supporting both database-to-database and file-to-database loads.',
      image: '/portfolio/images/candor_data.png',
      tags: ['ETL Pipeline', 'Data Mapping', 'Bulk Loading'],
      github: 'https://github.com/vasanthvk77/candor-data-platform',
    },
    {
      title: 'Prodesx HRM',
      category: 'Enterprise HRM',
      subtitle: 'Attendance & HR Automation',
      company: 'Prodesx Info Tech',
      tech: ['Flutter', '.NET', 'SQL Server', 'RDLC'],
      description: 'Worked on facial detection integration for employee attendance in a Flutter mobile application, retrieving and processing employee login/session details from hardware biometric punching devices. Developed standard administrative modules including department, organization, and employee profile management, as well as automatic calculations for PF (Provident Fund) and ESI (Employee State Insurance) benefits.',
      image: '/portfolio/images/prodesx_hrm.png',
      tags: ['Face Detection', 'Biometric Integration', 'Flutter App'],
      github: 'https://github.com/vasanthvk77',
    },
    {
      title: 'Service ERP',
      category: 'Enterprise ERP',
      subtitle: 'Service Lifecycle Management',
      company: 'Prodesx Info Tech',
      tech: ['Flutter', '.NET', 'SQL Server', 'RDLC'],
      description: 'Developed and completed a comprehensive service lifecycle system in a Flutter mobile application. Implemented features to assign service tasks to technicians, track task progress through a robust 9-stage workflow, register client complaints, track replacement parts/product costs, manage service charges, and record final delivery details.',
      image: '/portfolio/images/service_erp.png',
      tags: ['Service Lifecycle', '9-Stage Workflow', 'Flutter App'],
      github: 'https://github.com/vasanthvk77',
    },
  ],
  education: [
    {
      degree: 'B.E. – Computer Science and Engineering',
      institution: 'RVS College of Engineering & Technology',
      year: '2021 – 2025',
      grade: 'CGPA: 8',
    },
  ],
  certifications: [
    { name: 'Programming in Java', issuer: 'Elysium (Internship Certificate)' },
    { name: 'Web Development', issuer: 'EZIO Skill Academy' },
    { name: 'Web Development', issuer: 'ICT Academy (Virtual)' },
    { name: 'Programming in Java', issuer: 'NPTEL (65%)' },
  ],
};
