export const portfolioData = {
  personalInfo: {
    name: 'Vasanthakumar B',
    title: 'Fullstack Developer',
    email: 'vasanth2004vk@gmail.com',
    phone: '9514203043',
    linkedin: 'https://www.linkedin.com/in/vasanthakumar-b-6a9102293/',
    github: 'https://github.com/vasanthvk77',
    profileSummary: `Fullstack Developer with experience building end-to-end digital products — scalable backends, RESTful APIs, responsive web apps, and cross-platform mobile applications. Currently working at Prodesx Info Tech, previously at Cygnus Software, delivering real-world solutions across AI automation, ETL workflows, and system integration.
My stack includes Python, FastAPI, Flask, and .NET on the backend, React for web, Flutter for mobile, and SQL & MongoDB for data — with a consistent focus on clean, production-ready code across the full lifecycle.`,
  },
  skills: {
    'Programming & Backend': ['Python', 'Flask', 'FastAPI', '.NET', 'MySQL', 'PostgreSQL', 'SQL Server', 'MongoDB'],
    'Core Concepts': ['Data Structures', 'OOP', 'REST API Development', 'ETL', 'AI Automation'],
    'Frontend Exposure': ['HTML', 'CSS', 'Bootstrap', 'React', 'Flutter', 'Three.js'],
    'Tools & Platforms': ['Git', 'Railway', 'VS Code', 'Cursor', 'Antigravity', 'Vercel'],
    'Additional Skills': ['JSON', 'Agile Methodologies', 'Video Editing (DaVinci Resolve)', 'Photo Editing (Canva)'],
  },
  experience: [
    {
      role: 'Full Stack Developer',
      company: 'Prodesx Info Tech',
      date: 'March 2026 – Present',
      location: 'Coimbatore, Tamil Nadu',
     description: [
  'Developing an enterprise HRM platform using React.js, Flutter, ASP.NET Core, and SQL Server.',
  'Building Employee, Attendance, Leave, Payroll, and Role-Based Access modules.',
  'Creating responsive web and mobile interfaces with React.js and Flutter.',
  'Contributing to API development, database design, testing, and product release activities.'
]
    },
    {
      role: 'Fullstack Developer',
      company: 'Cygnus Softwares',
      date: 'June 2025 – March 2026',
      location: 'Coimbatore, Tamil Nadu',
      description: [
  'Developed scalable backend applications using Python FastAPI, Flask, SQL, and MongoDB.',
  'Designed API integrations, authentication systems, and automated data processing workflows.',
  'Built AI-driven solutions for email automation, data classification, and ETL processing.',
  'Performed testing, debugging, deployment support, and requirement analysis across multiple projects.'
]
    },
  ],
  // projects: [
  //   {
  //     title: 'ADA Checker Web Application',
  //     category: 'Web Accessibility',
  //     subtitle: 'Audit & Compliance Tool',
  //     company: 'Prodesx Tech',
  //     tech: ['React', 'Python FastAPI', 'JavaScript'],
  //     description: 'Worked on an ADA Checker web application that scans websites for ADA and WCAG accessibility violations. Built a FastAPI backend to audit URLs and generate detailed, actionable accessibility reports.',
  //     image: '/portfolio/images/ada_checker.png',
  //     tags: ['Accessibility Audit', 'WCAG 2.1', 'FastAPI Backend'],
  //     github: 'https://github.com/vasanthvk77/ada-checker',
  //   },
  //   {
  //     title: 'ATM Transaction Web Application',
  //     category: 'FinTech',
  //     subtitle: 'Banking Simulation',
  //     company: 'Personal Project',
  //     tech: ['React', 'Python Flask', 'SQL'],
  //     description: 'Developed a web application simulating ATM operations, including login, balance checking, deposits, withdrawals, and transaction history.',
  //     image: '/portfolio/images/atm.png',
  //     tags: ['Transaction Logic', 'SQL Integration', 'Secure Login'],
  //     github: 'https://github.com/vasanthvk77/atm-transaction',
  //   },
  //   {
  //     title: 'Sales Enquiry Automation',
  //     category: 'AI Automation',
  //     subtitle: 'Intelligent Lead Management',
  //     company: 'Cygnus Softwares',
  //     tech: ['React', 'Python FastAPI', 'MySQL'],
  //     description: 'Worked on a hotel sales-enquiry automation system that reads inbound emails, classifies them using AI, extracts key details, and sends acknowledgement and manager summary emails automatically.',
  //     image: '/portfolio/images/sales_enquiry.png',
  //     tags: ['AI Classification', 'Email Processing', 'Automation'],
  //     github: 'https://github.com/vasanthvk77/sales-enquiry-automation',
  //   },
  //   {
  //     title: 'Sign Language Generation',
  //     category: 'AI & Accessibility',
  //     subtitle: 'Spoken Audio to Sign Animation',
  //     company: 'Academic Project',
  //     tech: ['HTML', 'CSS', 'Javascript', 'Python Flask'],
  //     description: 'Developed an intelligent system that converts spoken audio into text and then translates that text into sign-language animations.',
  //     image: '/portfolio/images/sign_language.png',
  //     tags: ['Speech-to-Text', '3D Animations', 'Accessibility'],
  //     github: 'https://github.com/vasanthvk77/sign-language-generator',
  //   },
  //   {
  //     title: 'Candor Data Platform',
  //     category: 'Data Engineering',
  //     subtitle: 'Visual ETL Pipeline',
  //     company: 'Cygnus Softwares',
  //     tech: ['Typescript', 'Python FastAPI', 'MySQL', 'PostgreSQL'],
  //     description: 'Worked on a desktop ETL platform that lets users visually define, configure, and run complete data pipelines, supporting both database-to-database and file-to-database loads.',
  //     image: '/portfolio/images/candor_data.png',
  //     tags: ['ETL Pipeline', 'Data Mapping', 'Bulk Loading'],
  //     github: 'https://github.com/vasanthvk77/candor-data-platform',
  //   },
  //   {
  //     title: 'Prodesx HRM',
  //     category: 'Enterprise HRM',
  //     subtitle: 'Attendance & HR Automation',
  //     company: 'Prodesx Info Tech',
  //     tech: ['Flutter', '.NET', 'SQL Server', 'RDLC'],
  //     description: 'Worked on facial detection integration for employee attendance in a Flutter mobile application, retrieving and processing employee login/session details from hardware biometric punching devices. Developed standard administrative modules including department, organization, and employee profile management, as well as automatic calculations for PF (Provident Fund) and ESI (Employee State Insurance) benefits.',
  //     image: '/portfolio/images/prodesx_hrm.png',
  //     tags: ['Face Detection', 'Biometric Integration', 'Flutter App'],
  //     github: 'https://github.com/vasanthvk77',
  //   },
  //   {
  //     title: 'Service ERP',
  //     category: 'Enterprise ERP',
  //     subtitle: 'Service Lifecycle Management',
  //     company: 'Prodesx Info Tech',
  //     tech: ['Flutter', '.NET', 'SQL Server', 'RDLC'],
  //     description: 'Developed and completed a comprehensive service lifecycle system in a Flutter mobile application. Implemented features to assign service tasks to technicians, track task progress through a robust 9-stage workflow, register client complaints, track replacement parts/product costs, manage service charges, and record final delivery details.',
  //     image: '/portfolio/images/service_erp.png',
  //     tags: ['Service Lifecycle', '9-Stage Workflow', 'Flutter App'],
  //     github: 'https://github.com/vasanthvk77',
  //   },
  // ],
  projects: [
    {
      title: 'Service ERP',
      category: 'Enterprise ERP',
      subtitle: 'Service Lifecycle Management',
      company: 'Prodesx Info Tech',
      tech: ['Flutter', '.NET', 'SQL Server', 'RDLC'],
      description: 'Developed and completed a comprehensive service lifecycle system in a Flutter mobile application. Implemented features to assign service tasks to technicians, track task progress through a robust 9-stage workflow, register client complaints, track replacement parts/product costs, manage service charges, and record final delivery details.',
      image: '/images/service_erp.png',
      tags: ['Service Lifecycle', '9-Stage Workflow', 'Flutter App'],
      github: 'https://github.com/vasanthvk77',
    },
{
      title: 'Prodesx HRM',
      category: 'Enterprise HRM',
      subtitle: 'Attendance & HR Automation',
      company: 'Prodesx Info Tech',
      tech: ['Flutter', '.NET', 'SQL Server', 'RDLC'],
      description: 'Worked on facial detection integration for employee attendance in a Flutter mobile application, retrieving and processing employee login/session details from hardware biometric punching devices. Developed standard administrative modules including department, organization, and employee profile management, as well as automatic calculations for PF (Provident Fund) and ESI (Employee State Insurance) benefits.',
      image: '/images/prodesx_hrm.png',
      tags: ['Face Detection', 'Biometric Integration', 'Flutter App'],
      github: 'https://github.com/vasanthvk77',
    },
{
      title: 'Candor Data Platform',
      category: 'Data Engineering',
      subtitle: 'Visual ETL Pipeline',
      company: 'Cygnus Softwares',
      tech: ['Typescript', 'Python FastAPI', 'MySQL', 'PostgreSQL'],
      description: 'Worked on a desktop ETL platform that lets users visually define, configure, and run complete data pipelines, supporting both database-to-database and file-to-database loads.',
      image: '/images/candor_data.png',
      tags: ['ETL Pipeline', 'Data Mapping', 'Bulk Loading'],
      github: 'https://github.com/vasanthvk77/candor-data-platform',
    },
{
      title: 'Sales Enquiry Automation',
      category: 'AI Automation',
      subtitle: 'Intelligent Lead Management',
      company: 'Cygnus Softwares',
      tech: ['React', 'Python FastAPI', 'MySQL'],
      description: 'Worked on a hotel sales-enquiry automation system that reads inbound emails, classifies them using AI, extracts key details, and sends acknowledgement and manager summary emails automatically.',
      image: '/images/sales_enquiry.png',
      tags: ['AI Classification', 'Email Processing', 'Automation'],
      github: 'https://github.com/vasanthvk77/sales-enquiry-automation',
    },
{
      title: 'ADA Checker',
      category: 'Web Accessibility',
      subtitle: 'Audit & Compliance Tool',
      company: 'Cygnus Softwares',
      tech: ['React', 'Python FastAPI', 'JavaScript'],
      description: 'Worked on an ADA Checker web application that scans websites for ADA and WCAG accessibility violations. Built a FastAPI backend to audit URLs and generate detailed, actionable accessibility reports.',
      image: '/images/ada_checker.png',
      tags: ['Accessibility Audit', 'WCAG 2.1', 'FastAPI Backend'],
      github: 'https://github.com/vasanthvk77/ada-checker',
    },
{
      title: 'ATM Transaction Web Application',
      category: 'FinTech',
      subtitle: 'Banking Simulation',
      company: 'Personal Project',
      tech: ['React', 'Python Flask', 'SQL'],
      description: 'Developed a web application simulating ATM operations, including login, balance checking, deposits, withdrawals, and transaction history.',
      image: '/images/atm.png',
      tags: ['Transaction Logic', 'SQL Integration', 'Secure Login'],
      github: 'https://github.com/vasanthvk77/atm-transaction',
    },
 {
      title: 'Sign Language Generation',
      category: 'AI & Accessibility',
      subtitle: 'Spoken Audio to Sign Animation',
      company: 'Academic Project',
      tech: ['HTML', 'CSS', 'Javascript', 'Python Flask'],
      description: 'Developed an intelligent system that converts spoken audio into text and then translates that text into sign-language animations.',
      image: '/images/sign_language.png',
      tags: ['Speech-to-Text', '3D Animations', 'Accessibility'],
      github: 'https://github.com/vasanthvk77/sign-language-generator',
    },


  ],
  education: [
    {
      degree: 'B.E. – Computer Science and Engineering',
      institution: 'RVS College of Engineering & Technology',
      year: '2021 – 2025',
      grade: 'CGPA: 8',
    },
  ],
  certifications: [
    { name: 'Programming in Java', issuer: 'Elysium (Internship Certificate)' },
    { name: 'Web Development', issuer: 'EZIO Skill Academy' },
    { name: 'Web Development', issuer: 'ICT Academy (Virtual)' },
    { name: 'Programming in Java', issuer: 'NPTEL (65%)' },
  ],
};
